'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Resources.Driver
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option or rebuild the Visual Studio project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class View
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources.Driver.View", Global.System.Reflection.[Assembly].Load("App_GlobalResources"))
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Applies to.
        '''</summary>
        Friend Shared ReadOnly Property AppliesTo() As String
            Get
                Return ResourceManager.GetString("AppliesTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Color.
        '''</summary>
        Friend Shared ReadOnly Property Color() As String
            Get
                Return ResourceManager.GetString("Color", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deleting a driver.
        '''</summary>
        Friend Shared ReadOnly Property DeletingDriver() As String
            Get
                Return ResourceManager.GetString("DeletingDriver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Documents.
        '''</summary>
        Friend Shared ReadOnly Property Documents() As String
            Get
                Return ResourceManager.GetString("Documents", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Driver.
        '''</summary>
        Friend Shared ReadOnly Property Driver() As String
            Get
                Return ResourceManager.GetString("Driver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Drivers.
        '''</summary>
        Friend Shared ReadOnly Property Drivers() As String
            Get
                Return ResourceManager.GetString("Drivers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update.
        '''</summary>
        Friend Shared ReadOnly Property DriverUpdate() As String
            Get
                Return ResourceManager.GetString("DriverUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email.
        '''</summary>
        Friend Shared ReadOnly Property Email() As String
            Get
                Return ResourceManager.GetString("Email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extras for Travel.
        '''</summary>
        Friend Shared ReadOnly Property ExtrasForTravel() As String
            Get
                Return ResourceManager.GetString("ExtrasForTravel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First Name.
        '''</summary>
        Friend Shared ReadOnly Property FirstName() As String
            Get
                Return ResourceManager.GetString("FirstName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ID.
        '''</summary>
        Friend Shared ReadOnly Property ID() As String
            Get
                Return ResourceManager.GetString("ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Identifier.
        '''</summary>
        Friend Shared ReadOnly Property Identifier() As String
            Get
                Return ResourceManager.GetString("Identifier", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LastName.
        '''</summary>
        Friend Shared ReadOnly Property LastName() As String
            Get
                Return ResourceManager.GetString("LastName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Main Board.
        '''</summary>
        Friend Shared ReadOnly Property MainBoard() As String
            Get
                Return ResourceManager.GetString("MainBoard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Manufacturer.
        '''</summary>
        Friend Shared ReadOnly Property Manufacturer() As String
            Get
                Return ResourceManager.GetString("Manufacturer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Model.
        '''</summary>
        Friend Shared ReadOnly Property Model() As String
            Get
                Return ResourceManager.GetString("Model", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of Passenger.
        '''</summary>
        Friend Shared ReadOnly Property NimberOfPassenger() As String
            Get
                Return ResourceManager.GetString("NimberOfPassenger", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Logout.
        '''</summary>
        Friend Shared ReadOnly Property Output() As String
            Get
                Return ResourceManager.GetString("Output", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phone.
        '''</summary>
        Friend Shared ReadOnly Property Phone() As String
            Get
                Return ResourceManager.GetString("Phone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Promotions.
        '''</summary>
        Friend Shared ReadOnly Property Promotions() As String
            Get
                Return ResourceManager.GetString("Promotions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Registration.
        '''</summary>
        Friend Shared ReadOnly Property Registration() As String
            Get
                Return ResourceManager.GetString("Registration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Friend Shared ReadOnly Property Situation() As String
            Get
                Return ResourceManager.GetString("Situation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ride.
        '''</summary>
        Friend Shared ReadOnly Property Travel() As String
            Get
                Return ResourceManager.GetString("Travel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Trip Type.
        '''</summary>
        Friend Shared ReadOnly Property TripType() As String
            Get
                Return ResourceManager.GetString("TripType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type.
        '''</summary>
        Friend Shared ReadOnly Property Type() As String
            Get
                Return ResourceManager.GetString("Type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Users.
        '''</summary>
        Friend Shared ReadOnly Property Users() As String
            Get
                Return ResourceManager.GetString("Users", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Validation.
        '''</summary>
        Friend Shared ReadOnly Property Validation() As String
            Get
                Return ResourceManager.GetString("Validation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Valid From.
        '''</summary>
        Friend Shared ReadOnly Property ValidFrom() As String
            Get
                Return ResourceManager.GetString("ValidFrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Valid To.
        '''</summary>
        Friend Shared ReadOnly Property ValidTo() As String
            Get
                Return ResourceManager.GetString("ValidTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vehicle.
        '''</summary>
        Friend Shared ReadOnly Property Vehicle() As String
            Get
                Return ResourceManager.GetString("Vehicle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vehicle Update.
        '''</summary>
        Friend Shared ReadOnly Property VehicleUpdate() As String
            Get
                Return ResourceManager.GetString("VehicleUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Watch.
        '''</summary>
        Friend Shared ReadOnly Property Watch() As String
            Get
                Return ResourceManager.GetString("Watch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Watch Driver.
        '''</summary>
        Friend Shared ReadOnly Property WatchDriver() As String
            Get
                Return ResourceManager.GetString("WatchDriver", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
